/*@ begin PerfTuning (
 def build {
  arg build_command = 'gcc -O0';
 }
 def performance_counter {
  arg method = 'basic timer';
  arg repetitions = 10;
 }
 def performance_params {
  param UF[] = range(1,33);
 }

 def input_params {
  param N[] = [1000,10000000];
 }

 def input_vars {
  decl static double y[N] = random;
  decl double a1 = random;
  decl double a2 = random;
  decl double a3 = random;
  decl double a4 = random;
  decl static double x1[N] = random;
  decl static double x2[N] = random;
  decl static double x3[N] = random;
  decl static double x4[N] = random;
 }

 def search {
  arg algorithm = 'Exhaustive';
 }
) @*/
if ((N<=1000)) {

/**-- (Generated by Orio) 
Best performance cost: 
  [4.912e-06, 3.916e-06, 3.82e-06, 3.806e-06, 3.763e-06, 3.766e-06, 3.827e-06, 3.779e-06, 3.769e-06, 3.767e-06] 
Tuned for specific problem sizes: 
  N = 1000 
Best performance parameters: 
  UF = 2 
--**/


int i;

/*@ begin Loop ( 
    transform Unroll(ufactor=UF) 
    for (i=0; i<=N-1; i++)
    {

      
      y[i] = y[i] + a1*x1[i] + a2*x2[i] + a3*x3[i];

    }
) @*/
for (int loop_loop_38=0; loop_loop_38 < 1; loop_loop_38++)  {
    int i;
    for (i = 0; i <= N - 2; i = i + 2) {
      y[i] = y[i] + a1 * x1[i] + a2 * x2[i] + a3 * x3[i];
      y[(i + 1)] = y[(i + 1)] + a1 * x1[(i + 1)] + a2 * x2[(i + 1)] + a3 * x3[(i + 1)];
    }
    for (i = N - ((N - (0)) % 2); i <= N - 1; i = i + 1) 
      y[i] = y[i] + a1 * x1[i] + a2 * x2[i] + a3 * x3[i];
  }
/*@ end @*/

} else if ((N<=10000000)) {

/**-- (Generated by Orio) 
Best performance cost: 
  [0.0425481, 0.0423204, 0.0426107, 0.0426249, 0.0465825, 0.0423891, 0.0423293, 0.0419785, 0.0421441, 0.0422494] 
Tuned for specific problem sizes: 
  N = 10000000 
Best performance parameters: 
  UF = 3 
--**/


int i;

/*@ begin Loop ( 
    transform Unroll(ufactor=UF) 
    for (i=0; i<=N-1; i++)
    {

      
      y[i] = y[i] + a1*x1[i] + a2*x2[i] + a3*x3[i];

    }
) @*/
for (int loop_loop_38=0; loop_loop_38 < 1; loop_loop_38++)  {
    int i;
    for (i = 0; i <= N - 3; i = i + 3) {
      y[i] = y[i] + a1 * x1[i] + a2 * x2[i] + a3 * x3[i];
      y[(i + 1)] = y[(i + 1)] + a1 * x1[(i + 1)] + a2 * x2[(i + 1)] + a3 * x3[(i + 1)];
      y[(i + 2)] = y[(i + 2)] + a1 * x1[(i + 2)] + a2 * x2[(i + 2)] + a3 * x3[(i + 2)];
    }
    for (i = N - ((N - (0)) % 3); i <= N - 1; i = i + 1) 
      y[i] = y[i] + a1 * x1[i] + a2 * x2[i] + a3 * x3[i];
  }
/*@ end @*/

}
/*@ end @*/

